### ISSUE TITLE
Change maximally connected component logic in spawnReplanning

### ISSUE THREAD

**Issue by FedericoPecora** [FedericoPecora/coordination_oru#3]
Instead of a maximally connected component, the "other robots" should simply be the ones reachable by DFS on the transpose of the dep graph (from all the deadlocked robots).

**Comment by annamannucci** [comment]
Hi Federico, 

note that the dep graph used when re-planning stores only the closest dependency for each robot. Thus, for each vertex it exists just one outgoing arc, that is, the maximally connected component is equivalent to the DFS on the transposed graph. Please, double check the correctness of my sentence.

Best,

Anna Mannucci
