### ISSUE TITLE
Possible bug in the OccupancyMap class

### ISSUE THREAD

**Issue by annamannucci** [FedericoPecora/coordination_oru#4]
Hi Federico,

Please, check the following issue in the OccupancyMap class:

public void clearObstacles() {
		**this.bimg = this.bimg_original;**
		this.obstacles.clear();
	}

I suspect this is corrupting the bimg_original map during time. I checked it in the ParkingArrayNew example, where the re-planning does not work correctly in the current version of the code.

One possible way may be to use the deep copy
**this.bimg = deepCopy(this.bimg_original);**
which it seems to work fine, but it is clearly inefficient. 
What about clearing all the geometries in the current obstacles list? 
Then, the bimg_original may not really be required. Let me know if I or you may solve the issue.

Best,

Anna

**Comment by annamannucci** [comment]
I was thinking about something like this, but it does not work.
	public void clearObstacles() {
		fillObstacles(Color.white, (Geometry[]) this.obstacles.toArray());
		this.obstacles.clear();
	}
	
	public void addObstacles(Geometry ... obstacles) {
		fillObstacles(Color.black, obstacles);
		for (Geometry g : obstacles) this.obstacles.add(g);
		this.createOccupancyMap();
	}
	
	protected void fillObstacles(Color color, Geometry ... obstacles) {
		Graphics2D g2 = bimg.createGraphics();
		ShapeWriter writer = new ShapeWriter();
		g2.setPaint(color);
		for (Geometry g : obstacles) {
			AffineTransformation at = new AffineTransformation();
			at.scale(1.0/mapResolution, -1.0/mapResolution);
			at.translate(0, bimg.getHeight());
			Geometry scaledGeom = at.transform(g);
			Shape shape = writer.toShape(scaledGeom);
			//System.out.println("Shape: " + shape.getBounds2D());
			g2.fill(shape);
		}
		g2.dispose();

	}

**Comment by FedericoPecora** [comment]
Yes, corrected, thank you! Note that there was another issue in ParkingArrayNew, namely that the radius for collision checking used in the planner was as large as the robot, so it failed to replan most of the time. the example has now been corrected, but this may be an issue in other examples.
